services:

  ai-service:
    build: .
    container_name: ai_gym_ai_service
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      LM_STUDIO_URL: "http://host.docker.internal:2223"
      LLM_MODEL: "google/gemma-3-4b"
      USDA_API_KEY: "PGzaboN74Pr9iuNk3PfINBX1wkdkpzcpvpV92CF0"

    command:
      - uvicorn
      - main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"